### ISSUE TITLE
Turtle and Pocket peripheral examples??

### ISSUE THREAD

**Issue by Merith-TK** [Prunoideae/KubeJS-CC#1]
would it be possible to make this allow configuring peripherals for turtles and pocket computers,

**Comment by Prunoideae** [comment]
This mod can only add peripherals to blocks.

Turtles can access the block peripherals by calling `peripheral.wrap()` when nearby, for others then I don't know.

**Comment by Merith-TK** [comment]
Well, the idea was to add blocks/items as peripherals for Turtles/Pocket, since they have their own peripheral registry as what is considered an "upgrade" or not
